"""
Memory layer for the Slack AI Support Agent.

Provides two types of memory:
  1. Short-term (conversation memory): tracks the current thread's message
     history so the LLM can refer back to earlier turns in a multi-turn
     conversation within the same Slack thread.

  2. Long-term (episodic memory): stores summaries of resolved past
     conversations so the agent can recall what it previously told a user
     or what a common question's accepted answer was. Persisted to SQLite.

Why memory?
  Without memory, every message is treated as a fresh query. This forces
  users to repeat context ("as I mentioned earlier…") and prevents the
  agent from giving follow-up answers that build on prior turns.

Design:
  - Short-term memory is keyed by Slack thread_ts (one per thread)
  - Long-term memory is keyed by user_id + topic hash (persistent)
  - Both stores enforce capacity limits to prevent unbounded growth
  - Long-term memory summaries are generated by the LLM at end-of-thread

Best practices followed:
  - Separation of short-term (in-process dict) vs long-term (persistent DB)
  - TTL-based expiry for short-term entries (default: 2 hours)
  - Token budget enforcement: short-term context is trimmed to fit within
    MAX_CONTEXT_CHARS before being injected into the prompt
  - Explicit memory types match the MemGPT / ReAct agent literature
"""
from __future__ import annotations

import hashlib
import json
import logging
import time
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from sqlalchemy import Column, DateTime, String, Table, Text, MetaData, select, insert, update
from sqlalchemy import create_engine

from agent.config import config

logger = logging.getLogger(__name__)


# ══════════════════════════════════════════════════════════════════════
# Data models
# ══════════════════════════════════════════════════════════════════════

@dataclass
class ConversationTurn:
    role: str          # "user" | "assistant" | "tool"
    content: str
    timestamp: float = field(default_factory=time.time)
    tool_name: Optional[str] = None   # set for role="tool"

    def to_llm_message(self) -> dict:
        msg = {"role": self.role, "content": self.content}
        if self.tool_name:
            msg["name"] = self.tool_name
        return msg


@dataclass
class ConversationMemory:
    """
    Short-term memory for a single Slack thread.
    Stores the sequence of turns (user messages + assistant replies + tool results).
    """
    thread_ts: str
    channel_id: str
    turns: list[ConversationTurn] = field(default_factory=list)
    created_at: float = field(default_factory=time.time)
    last_updated: float = field(default_factory=time.time)

    # ── Capacity control ──────────────────────────────────────────────

    MAX_TURNS = 20         # maximum turns before oldest are dropped
    MAX_CHARS = 8000       # maximum total characters before trimming

    def add_turn(self, role: str, content: str, tool_name: Optional[str] = None) -> None:
        self.turns.append(ConversationTurn(role=role, content=content, tool_name=tool_name))
        self.last_updated = time.time()
        self._enforce_limits()

    def _enforce_limits(self) -> None:
        """Drop oldest turns when limits are exceeded."""
        # Hard turn limit
        while len(self.turns) > self.MAX_TURNS:
            self.turns.pop(0)
        # Soft character limit — drop oldest until within budget
        while self._total_chars() > self.MAX_CHARS and len(self.turns) > 2:
            self.turns.pop(0)

    def _total_chars(self) -> int:
        return sum(len(t.content) for t in self.turns)

    def to_llm_messages(self) -> list[dict]:
        """Format all turns as LLM-ready message dicts."""
        return [t.to_llm_message() for t in self.turns]

    def format_for_prompt(self, max_chars: int = 3000) -> str:
        """Format conversation history as a readable string for prompt injection."""
        if not self.turns:
            return ""
        lines = ["--- Prior conversation in this thread ---"]
        chars = 0
        # Walk turns in reverse to include most recent first
        for turn in reversed(self.turns[:-1]):   # exclude the current turn
            label = {"user": "User", "assistant": "Bot", "tool": f"Tool({turn.tool_name})"}.get(turn.role, turn.role)
            snippet = turn.content[:400]
            line = f"{label}: {snippet}"
            if chars + len(line) > max_chars:
                break
            lines.insert(1, line)
            chars += len(line)
        lines.append("--- End prior conversation ---")
        return "\n".join(lines) if len(lines) > 2 else ""

    def is_multi_turn(self) -> bool:
        return len([t for t in self.turns if t.role == "user"]) > 1

    @property
    def turn_count(self) -> int:
        return len(self.turns)


# ══════════════════════════════════════════════════════════════════════
# Short-term memory store
# ══════════════════════════════════════════════════════════════════════

class ShortTermMemory:
    """
    In-process dict keyed by thread_ts.
    Automatically expires entries after TTL_SECONDS.
    """

    TTL_SECONDS = 7200    # 2 hours — matches a typical Slack working session
    MAX_THREADS = 500     # cap total threads to prevent memory leaks

    def __init__(self):
        self._store: dict[str, ConversationMemory] = {}

    def get_or_create(self, thread_ts: str, channel_id: str) -> ConversationMemory:
        self._evict_expired()
        if thread_ts not in self._store:
            self._store[thread_ts] = ConversationMemory(
                thread_ts=thread_ts, channel_id=channel_id
            )
        return self._store[thread_ts]

    def get(self, thread_ts: str) -> Optional[ConversationMemory]:
        self._evict_expired()
        return self._store.get(thread_ts)

    def delete(self, thread_ts: str) -> None:
        self._store.pop(thread_ts, None)

    def _evict_expired(self) -> None:
        now = time.time()
        expired = [k for k, v in self._store.items()
                   if now - v.last_updated > self.TTL_SECONDS]
        for k in expired:
            del self._store[k]
        # Also enforce max thread count (LRU-style: drop oldest)
        while len(self._store) > self.MAX_THREADS:
            oldest_key = min(self._store, key=lambda k: self._store[k].last_updated)
            del self._store[oldest_key]

    @property
    def active_thread_count(self) -> int:
        self._evict_expired()
        return len(self._store)


# ══════════════════════════════════════════════════════════════════════
# Long-term memory store (SQLite)
# ══════════════════════════════════════════════════════════════════════

_ltm_metadata = MetaData()

long_term_memory_table = Table(
    "long_term_memory",
    _ltm_metadata,
    Column("id", String, primary_key=True),        # hash(user_id + topic)
    Column("user_id", String, nullable=False, index=True),
    Column("topic_key", String, nullable=False),   # normalised topic
    Column("summary", Text, nullable=False),       # LLM-generated summary
    Column("channel_id", String),
    Column("thread_ts", String),
    Column("created_at", DateTime),
    Column("updated_at", DateTime),
    Column("access_count", String, default="1"),   # how often recalled
)


class LongTermMemory:
    """
    Persistent episodic memory: stores summaries of resolved conversations.

    When a Slack thread ends (no new messages for N minutes), the agent
    optionally summarises the conversation and stores it here.

    At query time, long-term memory is searched by topic similarity
    (simple keyword match — semantic search would be overkill for this store).
    """

    def __init__(self, database_url: str = config.database_url):
        engine = create_engine(database_url, echo=False)
        _ltm_metadata.create_all(engine)
        self._engine = engine

    def store(
        self,
        user_id: str,
        topic_key: str,
        summary: str,
        channel_id: str = "",
        thread_ts: str = "",
    ) -> str:
        """Store or update a memory entry. Returns the entry ID."""
        entry_id = self._make_id(user_id, topic_key)
        now = datetime.utcnow()
        with self._engine.begin() as conn:
            existing = conn.execute(
                select(long_term_memory_table.c.id)
                .where(long_term_memory_table.c.id == entry_id)
            ).fetchone()
            if existing:
                conn.execute(
                    update(long_term_memory_table)
                    .where(long_term_memory_table.c.id == entry_id)
                    .values(summary=summary, updated_at=now)
                )
            else:
                conn.execute(insert(long_term_memory_table).values(
                    id=entry_id, user_id=user_id, topic_key=topic_key,
                    summary=summary, channel_id=channel_id, thread_ts=thread_ts,
                    created_at=now, updated_at=now, access_count="1",
                ))
        logger.debug("LTM stored: user=%s topic=%s", user_id, topic_key)
        return entry_id

    def recall_for_user(self, user_id: str, limit: int = 5) -> list[dict]:
        """Retrieve recent memory entries for a specific user."""
        with self._engine.connect() as conn:
            rows = conn.execute(
                select(long_term_memory_table)
                .where(long_term_memory_table.c.user_id == user_id)
                .order_by(long_term_memory_table.c.updated_at.desc())
                .limit(limit)
            ).fetchall()
        return [dict(r._mapping) for r in rows]

    def search_by_topic(self, topic_query: str, limit: int = 3) -> list[dict]:
        """
        Simple keyword search over stored summaries.
        Not semantic — intentional for speed and simplicity.
        Upgrade path: embed summaries and store in the same vector store.
        """
        query_words = set(topic_query.lower().split())
        with self._engine.connect() as conn:
            rows = conn.execute(
                select(long_term_memory_table)
                .order_by(long_term_memory_table.c.updated_at.desc())
                .limit(200)
            ).fetchall()
        scored = []
        for row in rows:
            row_dict = dict(row._mapping)
            text = (row_dict.get("summary", "") + " " + row_dict.get("topic_key", "")).lower()
            score = sum(1 for w in query_words if w in text)
            if score > 0:
                scored.append((score, row_dict))
        scored.sort(key=lambda x: -x[0])
        return [r for _, r in scored[:limit]]

    def forget(self, entry_id: str) -> None:
        """Delete a specific memory entry (GDPR / user request)."""
        from sqlalchemy import delete as sa_delete
        with self._engine.begin() as conn:
            conn.execute(
                sa_delete(long_term_memory_table)
                .where(long_term_memory_table.c.id == entry_id)
            )

    def forget_user(self, user_id: str) -> int:
        """Delete all memory for a specific user. Returns count deleted."""
        from sqlalchemy import delete as sa_delete
        with self._engine.begin() as conn:
            result = conn.execute(
                sa_delete(long_term_memory_table)
                .where(long_term_memory_table.c.user_id == user_id)
            )
        return result.rowcount

    @staticmethod
    def _make_id(user_id: str, topic_key: str) -> str:
        raw = f"{user_id}::{topic_key.lower().strip()}"
        return hashlib.sha256(raw.encode()).hexdigest()[:24]
